version: "3"
services:
  db:
    container_name: h2
    image: oscarfonts/h2
    ports:
      - 1521:1521
      - 8081:81
    environment:
      H2_OPTIONS: -ifNotExists
    volumes:
      - ./H2/:/opt/h2-data
    restart: always

  app:
    build:
      context: .
      dockerfile: ../docker/enuriShopDocker/Dockerfile
    container_name: enuri_app
    ports:
      - 8880:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:tcp://h2:1521/enuriShop
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - db